In [16]:
## 导入库函数
from ortools.constraint_solver import routing_enums_pb2
from ortools.constraint_solver import pywrapcp
import numpy as np
import tsplib95
import matplotlib.pyplot as plt
%matplotlib inline

In [25]:
# martix_a & martix_b
import pandas as pd
from scipy.spatial.distance import pdist
from scipy.spatial.distance import squareform
sheet1_red=pd.read_excel(r'/home/jesse_chen/anaconda3/A_computer_science/数维B题/for_martix.xlsx',sheet_name='sheet1')
sheet2_blue=pd.read_excel(r'/home/jesse_chen/anaconda3/A_computer_science/数维B题/for_martix.xlsx',sheet_name='sheet2')
red=np.array(sheet1_red)
blue=np.array(sheet2_blue)
# red;blue是一个向量矩阵：euclidean代表欧式距离
distA=pdist(red*1000,metric='euclidean')
distB=pdist(blue*1000,metric='euclidean')
# 将distA;distB数组变成矩阵
dist_red = squareform(distA)
dist_blue = squareform(distB)
dataA = np.array(dist_red,dtype=object)
np.savetxt("martix_a.txt",dataA ,fmt="%d",delimiter=",")
dataA = np.loadtxt('martix_a.txt',delimiter=',')


[[    0.   305. 14334. ...  5206.  7214.  7612.]
 [  305.     0. 14313. ...  5364.  7392.  7827.]
 [14334. 14313.     0. ... 10451.  9866. 10886.]
 ...
 [ 5206.  5364. 10451. ...     0.  2076.  2860.]
 [ 7214.  7392.  9866. ...  2076.     0.  1247.]
 [ 7612.  7827. 10886. ...  2860.  1247.     0.]]
[[    0.           305.01905143 14334.04340222 ...  5206.85232747
   7214.10883551  7612.7769734 ]
 [  305.01905143     0.         14313.38325414 ...  5364.93352242
   7392.25526595  7827.3794946 ]
 [14334.04340222 14313.38325414     0.         ... 10451.79745881
   9866.84112099 10886.29056945]
 ...
 [ 5206.85232747  5364.93352242 10451.79745881 ...     0.
   2076.34895436  2860.28668887]
 [ 7214.10883551  7392.25526595  9866.84112099 ...  2076.34895436
      0.          1247.08433333]
 [ 7612.7769734   7827.3794946  10886.29056945 ...  2860.28668887
   1247.08433333     0.        ]]


In [18]:
#demand_a
import pandas as pd
def excel_one_line_to_list():
    df = pd.read_excel(r'/home/jesse_chen/anaconda3/A_computer_science/数维B题/Annex1：node＆link.xlsx',sheet_name='demand_a')  # 读取项目名称列,不要列名
    df_li = df.values.tolist()
    result = []
    for s_li in df_li:
        result.append(s_li[0])
    return result
demand_a=excel_one_line_to_list()

In [ ]:
# 给定数据目录并读入数据
data=[]
# 让节点编号从0开始
data["display_data"] = {k-1: v for k, v in data["display_data"].items()}
# 补充每个节点的demand数据
rng = np.random.default_rng(seed = 0)
data["demand"] = rng.integers(1, 11, data["dimension"]) # 随机生成[1, 10]的需求
# 车辆数据
n_vehicles = 4 # 车辆数
capacity = [250] * n_vehicles # 车辆最大负载
vehicle_start_idx = rng.integers(0, data["dimension"], n_vehicles) # 每辆车的起点
# 注意ortools是c++写的，它并不接受 np.int64，因此要转化为python原生的int类型
vehicle_start_idx = [i.item() for i in vehicle_start_idx]
vehicle_end_idx = rng.integers(0, data["dimension"], n_vehicles) # 每辆车的终点
vehicle_end_idx = [i.item() for i in vehicle_end_idx]

In [23]:
# 给定数据目录并读入数据
fname: str = "CVRP_Red_268"
input_fpath: str = r"/home/jesse_chen/anaconda3/A_computer_science/数维B题/" + fname
data = tsplib95.load(input_fpath).as_name_dict()
# 让节点编号从0开始
data["display_data"] = {k-1: v for k, v in data["display_data"].items()}
# 补充每个节点的demand数据
#rng = np.random.default_rng(seed = 0)
#data["demand"] = rng.integers(1, 11, data["dimension"]) # 随机生成[1, 10]的需求
data["demand"] = demand_a#考虑各节点士兵数量和坦克数量-----根据excel表得到：考虑比例：士兵和轻中重三种坦克=A2:A269+B2:B269*60+C2:C269*85*+D2:D269*100+E2:E269*5
# 车辆数据
n_vehicles = 100000 # 车辆数
capacity = [100] * n_vehicles # 车辆最大负载-------按比例增大 对应demand数量级
vehicle_start_idx = []# 每辆车的起点
vehicle_end_idx = []# 每辆车的终点
'''
vehicle_start_idx = rng.integers(0, data["dimension"], n_vehicles) # 每辆车的起点
# 注意ortools是c++写的，它并不接受 np.int64，因此要转化为python原生的int类型
vehicle_start_idx = [i.item() for i in vehicle_start_idx]
vehicle_end_idx = rng.integers(0, data["dimension"], n_vehicles) # 每辆车的终点
vehicle_end_idx = [i.item() for i in vehicle_end_idx]
'''

ParsingError: MatrixField(EDGE_WEIGHT_SECTION): item.0=>ParsingError("item.0=>ParsingError('could not convert text to number: 0,305,14334,14136,15170,14500,15016,15076,15130,14822,14310,14273,15144,14317,14310,14067,14283,14274,14311,14274,14278,14318,14373,2569,3021,556,984,2276,2174,2125,1984,2295,2602,3033,3094,1980,2221,1502,2250,3222,3239,4917,6376,12965,12810,15537,14988,12612,12249,12220,12197,12050,11941,15806,2821,1988,2088,3704,4145,7017,7250,14396,515,240,9324,9416,9926,9834,10340,10366,10345,10131,9894,11614,11452,12039,11986,10928,9976,9938,9212,8972,8672,11288,10986,10953,9793,10132,10173,7842,7969,12039,10591,10547,10410,10361,9798,9166,8635,10045,10142,8287,8114,10561,10510,10452,10218,10080,9946,9761,7355,12566,9920,10787,9692,10522,8976,9968,10309,11349,10742,10862,11031,11074,10499,10904,10288,10025,8327,8301,8366,12033,8350,10129,10148,10375,10820,10549,9866,11274,11200,9756,10180,11237,10701,10892,1994,3452,3460,3522,4071,4605,6319,10844,10868,10107,10123,10102,11709,10376,10367,10041,10801,10963,11509,1799,1782,1853,1875,1048,1864,1942,517,819,899,383,299,522,457,265,253,483,335,8967,6663,6644,12620,12353,2171,7518,9681,13983,10111,10108,12013,6770,5302,4612,4560,683,14641,13818,8356,11906,5045,4813,4788,4865,4747,4599,6268,3531,4317,4456,3682,2573,6742,6770,6861,8200,7058,7068,7016,6811,6927,12006,6880,6762,9000,12520,9047,11903,13112,14057,13164,11066,10949,6807,6761,6863,6791,6729,7308,6918,6790,6656,6086,7452,7568,7846,7967,7735,7540,7316,7085,6847,7030,7256,6797,5561,5467,5373,5361,5215,5206,7214,7612')"), item.1=>ParsingError("item.0=>ParsingError('could not convert text to number: 305,0,14313,14127,15207,14545,15039,15108,15162,14839,14306,14284,15182,14332,14322,14059,14275,14270,14307,14286,14293,14309,14352,2359,2834,251,838,2278,2200,2165,2168,2306,2530,2852,2905,1815,2249,1259,2259,3046,3062,4722,6199,12935,12777,15549,14993,12575,12194,12161,12132,11962,11818,15811,3124,2177,2381,3997,4438,7298,7529,14371,210,545,9506,9603,10095,9999,10515,10539,10511,10302,10064,11791,11631,12161,12108,11052,10106,10069,9352,9115,8820,11452,11135,11049,9972,10276,10317,8021,8157,12177,10756,10713,10567,10519,9964,9342,8821,10290,10287,8479,8310,10754,10701,10642,10407,10268,10134,9944,7484,12648,10124,10961,9800,10704,9199,10211,10488,11530,10916,11041,11216,11258,10663,11083,10468,10162,8417,8423,8489,12123,8435,10220,10235,10455,10899,10514,9787,11301,11226,9828,10266,11150,10778,10945,2166,3544,3550,3596,4060,4548,6205,10926,10952,10192,10210,10193,11654,10455,10445,10117,10878,11017,11520,1953,1940,2018,2036,1256,2037,2103,753,1115,1149,607,508,670,744,570,558,616,618,8999,6613,6591,12553,12292,2214,7669,9788,14048,10203,10211,12102,6902,5443,4760,4709,939,14641,13804,8440,11849,5080,4869,4852,4922,4809,4680,6124,3446,4208,4298,3524,2497,6845,6892,6964,8283,7136,7144,7086,6893,7010,11949,6976,6858,9285,12765,9351,12180,13371,14358,13469,11370,11254,6955,6908,7006,6933,6873,7445,7058,6931,6798,6231,7604,7731,8031,8165,7932,7735,7509,7276,7036,7232,7461,6990,5716,5635,5531,5522,5371,5364,7392,7827')"), item.2=>ParsingError("item.0=>ParsingError('could not convert text to number: 14334,14313,0,550,2915,3096,2229,2674,2680,1881,817,1494,2949,1677,1533,652,562,786,804,1523,1656,553,39,12520,12004,14302,13511,12057,12170,12232,12832,12041,11804,11944,11968,12701,12126,13462,12085,11759,11763,10783,9566,1427,1618,2034,1401,1881,2589,2732,2915,3758,5116,1965,15113,12858,14033,16043,16317,18686,18944,201,14304,14355,9451,9583,8851,8692,9017,8914,8677,8878,8880,9101,9196,6652,6663,6889,7395,7422,7999,8198,8454,8491,7895,5884,9241,7859,7825,9681,9895,7309,8607,8645,8274,8308,8719,9223,9670,12278,7880,9991,10146,9781,9705,9651,9616,9597,9581,9378,8613,4879,10271,8953,6808,9291,11106,12194,9154,9258,8982,9183,9459,9431,8559,9152,9254,7635,7171,7905,7911,5323,7057,6087,5959,5641,5366,3832,5046,3631,3666,5792,5901,4210,5355,4558,12755,11140,11121,10991,10262,9796,8596,5426,5514,5934,5969,6101,3028,5607,5573,5711,5292,4525,3114,16020,15993,16039,16070,15225,16026,16132,14752,14637,14981,14671,14615,14848,14176,14347,14371,14814,14526,5690,7743,7773,2687,2677,12191,9028,6779,4008,6126,6462,5263,9026,10141,10696,10740,13957,998,609,7030,2899,9389,9710,9783,9668,9810,10058,9042,10943,10327,10624,11252,11843,8541,8841,8458,7128,7937,7898,7872,8197,8113,2837,8337,8423,19947,24498,16905,22748,24567,22259,19709,18517,18330,9322,9340,9196,9209,9288,8822,9093,9184,9281,9702,9082,9324,9835,10256,10273,10269,10267,10270,10275,10596,10626,10408,10191,10464,10359,10392,10419,10451,9866,10886')"), and 264 more

In [ ]:
class TSP_DATA:
  '''用于读取数据、存放图的数据结构

  类内变量：
    必有：
      self.NAME         测试样例名称
      self.TYPE         测试样例类型  TSP ATSP
      self.DIMENSION.      维度
      self.EDGE_WEIGHT_TYPE   边权值计算方式 决定读取方式 
      self.matrix        矩阵形式数据
      self.table .       邻接表形式数据

    可能有：
      self.EDGE_WEIGHT_FORMAT
      self.EDGE_DATA_FORMAT
      self.NODE_COORD_TYPE required if EDGE_WEIGHT_TYPE is not WeightKind::Explicit
  
  '''
  # 初始化，读取数据，并获取表头的数据规约
  def __init__(self, path):
    """传入单个数据地址，读取并且加载数据的表头
    path:
      单个测试样例的数据地址
    """
    self.debug = True
    # 读取数据文件
    raw_data, name = self.read_any_file(path)
    # # 无论如何名字都是第0行
    # self.name = raw_data.split(':')[1]
    self.get_headline(raw_data)
    # 保证数据名称和文件名称相同
    assert self.NAME == name
    # 保证是TSP问题的文件
    assert 'TSP' in self.TYPE
    # 有数据区块 长条list
    self.rawnum = self.get_data_list(raw_data)
    # 计算邻接矩阵 和 邻接表
    if self.debug:
      print("原始数据：",self.rawnum)
    if self.EDGE_WEIGHT_TYPE == "EXPLICIT":
      self.matrix = self.get_adjacency_matrix()
      if self.debug:
        print("矩阵",self.matrix)
      # self.table = self.matrix_2_table()
    # else:
    #   coorodinate_table = self.get_coorodinate_table_from_raw()
    #   self.table = self.get_adjacency_table()
    #   self.matrix = self.table_2_matrix()


  def get_data_list(self, data_all):
    """ 返回数字数据，被关键字和EOF包裹。不做其他处理
    EXPLICIT EDGE_WEIGHT_SECTION 
      DGE_WEIGHT_SECTION
      0  273    0 1272  999    0  744  809 1519    0 1138  866  140 1425

    EUC_2D  NODE_COORD_SECTION
      NODE_COORD_SECTION
      1 4.35841e+02 5.87522e+02
      2 6.02539e+02 8.01704e+02
      有丢失城市的情况，补无穷
    
    return：
      EXPLICIT 一长条int的list，空格隔开
      else 三列 n行 list（划掉）
      else 一长条int的list，空格隔开
    
    update:
      数据还有浮点数，得改一下
      可能有‘  699'这样的数据，不能用数字判别，应该用 非字母逻辑
      
    """
    end_line = len(data_all)-2 # 去掉EOF -1 从零开始 -1
    print(data_all)

    # 距离矩阵
    if self.EDGE_WEIGHT_TYPE == 'EXPLICIT':
      # 此时是n*1的
      beging_line = 0
      
      for i in range(10):
        if 'EDGE_WEIGHT_SECTION' in data_all[0][i]:
          # 下一位开始是数据
          beging_line = i+1
          break
        else:
          pass
          #raise Exception("EDGE_WEIGHT_SECTION 关键字未找到")
      if self.debug:
        print("发现数据开头标志位置",beging_line)

      string_data = data_all[0][beging_line]
      for h in range(beging_line+1,end_line+1):
        # 清洗掉其他标签，如可视化等
        if data_all[0][h][0].isalpha():
          # 如果这条数据是字母，那么中断循环。由于数字有空格，不能用数字判别
          break
        # todo 中间是不是要人为加空格
        string_data = string_data + " " + data_all[0][h]
      string_data_split = string_data.strip().split(' ')
      list_data =  [float(i) for i in string_data_split if i.isdigit()]
      if self.debug:
        print(string_data_split)
        print(list_data)
    # 坐标
    else: 
      beging_line = 0
      # if not 'NODE_COORD_SECTION' in data_all[0]:
      #   raise Exception("NODE_COORD_SECTION 关键字未找到")
      for i in range(10):
        beging_line = beging_line+1
        if 'NODE_COORD_SECTION' in data_all[0][i]:
          break
              
      # 第一条单独获取
      string_data = data_all[0][beging_line]
      # 获取其余数字
      for h in range(beging_line+1,end_line+1):
        # 清洗掉其他标签，如可视化等
        if data_all[0][h][0].isalpha():
          # 如果这条数据是字母，那么中断循环。由于数字有空格，不能用数字判别
          break
        # todo 中间是不是要人为加空格
        string_data = string_data + ' ' + data_all[0][h]

      if self.debug:
        print("发现数据开头标志位置",beging_line)
        print("数据")
        print(data_all[0][0])
      string_data_split = string_data.strip().split(' ')
      # 使用浮点数 1e2就不用手动转换了      
      list_data =  [float(i) for i in string_data_split if i.isdigit()]
      if self.debug:
        print(string_data_split)
        print(list_data)

    # 这里取了简便 #todo
  
    return list_data

  # 获取表头数据规约
  def get_headline(self, raw_data):
    head_dict = {}
    head_index = 0
    # 获取字母表头(好像没啥用，但是逻辑更通畅了)
    for h in range(len(raw_data)):
      if not raw_data[0][h][0].isalpha():
        break
      else:
        head_index = head_index + 1
      
    # 最多只有10个类型的表头
    for i in range(head_index):
      if ':' not in raw_data[0][i]:
        break
      # 构建字典
      head_dict[raw_data[0][i].split(':')[0]] = raw_data[0][i].split(':')[1]
    
    # 从字典获取信息，去掉左右空格
    self.NAME = head_dict['NAME'].strip()
    self.TYPE = head_dict['TYPE'].strip()
    self.DIMENSION = int(head_dict['DIMENSION'].strip())
    self.EDGE_WEIGHT_TYPE = head_dict['EDGE_WEIGHT_TYPE'].strip()
    if self.TYPE == "CVRP": 
      # 载货问题时，需要卡车容量
      self.CAPACITY = head_dict['CAPACITY'].strip()
    else:
      pass

    if self.EDGE_WEIGHT_TYPE == "EXPLICIT": 
      # 距离在raw code中指定的情况下，要给出邻接矩阵存放方式
      # 数据开头  EDGE_WEIGHT_SECTION
      # 比如 UPPER_DIAG_ROW 上三角矩阵
      self.EDGE_WEIGHT_FORMAT = head_dict['EDGE_WEIGHT_FORMAT'].strip()
    else:
      if 'NODE_COORD_TYPE' in head_dict.keys():
        self.NODE_COORD_TYPE = head_dict['NODE_COORD_TYPE'].strip()
      # 但实际很多都没有
      # 理论上要满足： NODE_COORD_TYPE (required if EDGE_WEIGHT_TYPE is not WeightKind::Explicit): specifies how the coordinate for each node is given in the file. Represented by the enum CoordKind.
      # 数据开头：  NODE_COORD_SECTION
      pass
    
  # 读取文件，不予处理
  def read_any_file(self,thispath):
    # 判断是否是数据集
    if not os.path.isfile(thispath):
      raise Exception('数据读取报错，地址非文件')
    # 读取文件 raw数据
    df = pd.read_csv(thispath,header=None)
    # 文件名
    if check_sys == 'Linux':   # colab address
      name = thispath.split('/')[-1].split('.')[0]
    elif check_sys == 'Windows': # local address 
      name = thispath.split('\\')[-1].split('.')[0]
    else:
      raise EnvironmentError
    return df,name
  
  # 根据 EDGE_WEIGHT_TYPE 距离计算方式，返回距离
  def cal_a_distance_by_coordinate(self,a,b):
    '''
    按照 城市编号 a -> b ，给出两点之间的距离
    可能的距离定义式：https://docs.rs/tspf/0.3.0/tspf/enum.WeightKind.html
      Explicit   权重在数据文件中明确给出。直接读出来就是距离。
      Euc2d    二维欧几里得距离。
      Euc3d    三维欧几里得距离。
      Max2d    二维马氏距离。？？？？这是衡量矩阵的？？？？
      Max3d    三维马氏距离。
      Man2d    二维曼哈顿距离。
      Man3d    三维曼哈顿距离。
      Ceil2d    向上取整的二维欧几里得距离。
      Geo     地理距离。 既欧氏距离
      Att     问题的特殊距离函数att48和att532。
      Xray1    版本 1 晶体学问题的特殊距离函数。
      Xray2    版本 2 晶体学问题的特殊距离函数。
      Custom    用户定义的距离函数。
      Undefined  没有给出距离函数。
    '''
    if self.EDGE_WEIGHT_TYPE == "EUC_2D" or self.EDGE_WEIGHT_TYPE =="GEO":
      distance = (self.adjacency_table(a)[0]-self.adjacency_table(b)[0])**2+\
      (self.adjacency_table(a)[1]-self.adjacency_table(b)[1])**2

    elif self.EDGE_WEIGHT_TYPE == "EUC_3D":
      distance = abs((self.adjacency_table(a)[0]-self.adjacency_table(b)[0])**3+\
      (self.adjacency_table(a)[1]-self.adjacency_table(b)[1])**3)

    elif self.EDGE_WEIGHT_TYPE == "EXPLICIT":
      raise Exception("EXPLICIT距离必须由raw data的邻接矩阵给出")

    elif self.EDGE_WEIGHT_TYPE == "MAN_2D":
      distance = abs((self.adjacency_table(a)[0]-self.adjacency_table(a)[1])**2-\
      (self.adjacency_table(b)[0]-self.adjacency_table(b)[1])**2)

    elif self.EDGE_WEIGHT_TYPE == "MAN_3D":
      distance = abs((self.adjacency_table(a)[0]-self.adjacency_table(a)[1])**3-\
      (self.adjacency_table(b)[0]-self.adjacency_table(b)[1])**3)

    elif self.EDGE_WEIGHT_TYPE == "CEIL_2D":
      distance = int((self.adjacency_table(a)[0]-self.adjacency_table(b)[0])**2+\
      (self.adjacency_table(a)[1]-self.adjacency_table(b)[1])**2) + 1
    else: # 都不符合
      raise Exception("此类型距离未定义")
    return distance

  # 根据 TYPE 进行判断，返回邻接矩阵
  def get_adjacency_matrix(self):
    '''专用于TSP问题的原始数据转矩阵函数（由于ATSP距离不对称，优化不能用）
          
      当确认矩阵储存方式 EDGE_WEIGHT_TYPE 为 邻接矩阵 EXPLICIT 时
      self.EDGE_WEIGHT_FORMAT 保存矩阵储存格式
      self.rawnum 保存raw data中的所有数字
    矩阵存放形式
      Function    权重由WeightKind中所述的函数计算。
    FullMatrix   权重以完整矩阵形式给出。对应FULL_MATRIX于 TSPLIB 中的值。
    UpperRow    权重在上三角矩阵中按行给出，没有对角线条目。  对应UPPER_ROW于 TSPLIB 中的值。
    LowerRow    权重在下三角矩阵中给出，按行排列，没有对角线条目。 对应LOWE_ROW于 TSPLIB 中的值。
    UpperDiagRow  权重在上三角矩阵中给出，按行与对角线条目。  对应UPPER_DIAG_ROW于 TSPLIB 中的值。
    LowerDiagRow  权重在下三角矩阵中给出，按行与对角线条目。  对应LOWER_DIAG_ROW于 TSPLIB 中的值。
      UpperCol    权重在上三角矩阵中给出，没有对角线条目。  对应UPPER_COL于 TSPLIB 中的值。
      LowerCol    权重在下三角矩阵中给出，没有对角线条目。  对应LOWER_COL于 TSPLIB 中的值。
      UpperDiagCol  权重在上三角矩阵中给出，与对角线条目并列。  对应UPPER_DIAG_COL于 TSPLIB 中的值。
      LowerDiagCol  权重在下三角矩阵中给出，与对角线条目并列。  对应LOWER_DIAG_COL于 TSPLIB 中的值。
    Undefined    没有说明如何存储权重。
    '''
    # if self.TYPE == "TSP":
    matrix = []
    # 上三角，包含对角全0
    if self.EDGE_WEIGHT_FORMAT == "UPPER_DIAG_ROW":
      # 数据长度应该是：d + d-1 + d-2 +...+ 1 = (1+d)*d/2
      d = self.DIMENSION
      if not len(self.rawnum) == int((1+d)*d/2):
        raise Exception("获取的raw num数据量不对")
      for i in range(d):
        # 由于自己有0，第一行不填0，第二行补一个，第n行补n-1个
        row = [0 for j in range(i)]
        # left = sum 0 d d-1 \
        left = int( i*d-(0+i-1)*i/2 )
        right = int( (i+1)*d-(0+i)*(i+1)/2 )
        # right = sum d d-1 d-2 ... = i*d-(0+i-1)*i/2
        row = row + self.rawnum[left : right]
        matrix.append(row)
      # 上三角补全到完整矩阵
      m = np.array(matrix)
      matrix = (np.triu(m, k=1).T + np.triu(m, k=0)).tolist()

    # 下三角 包括对角线 LOWER_DIAG_ROW
    if self.EDGE_WEIGHT_FORMAT == "LOWER_DIAG_ROW":
      # 数据长度应该是：d + d-1 + d-2 +...+ 1 = (1+d)*d/2
      d = self.DIMENSION
      # 转化为上三角
      self.rawnum = self.rawnum.reverse()
      if not len(self.rawnum) == int((1+d)*d/2):
        raise Exception("获取的raw num数据量不对")
      for i in range(d):
        # 由于自己有0，第一行不填0，第二行补一个，第n行补n-1个
        row = [0 for j in range(i)]
        # left = sum 0 d d-1 \
        left = int( i*d-(0+i-1)*i/2 )
        right = int( (i+1)*d-(0+i)*(i+1)/2 )
        # right = sum d d-1 d-2 ... = i*d-(0+i-1)*i/2
        row = row + self.rawnum[left : right]
        matrix.append(row)
      # 下三角补全到完整矩阵
      m = np.array(matrix)
      matrix = (np.tril(m, k=1).T + np.tril(m, k=0)).tolist()

    # 上三角，不包含对角全0
    elif self.EDGE_WEIGHT_FORMAT == "UPPER_ROW":
      # 数据长度应该是：d + d-1 + d-2 +...+ 1 = (1+d)*d/2
      d = self.DIMENSION
      if not len(self.rawnum) == int((1+d)*d/2-d):
        raise Exception("获取的raw num数据量不对")
      for i in range(d):
        # 由于自己有0，第一行填1个0，第二行补2个，第n行补n个
        row = [0 for j in range(i+1)]
        # left = sum 0 d-1 d-2 
        if i == 0:
          left = 0
        else:
          left = int( d*(i-1) -(i-1)*i/2 )
        # right = sum d-1 d-2 d-3 ... = int(d*i -(1+i)i/2)
        right = int( d*i -(1+i)*i/2 )
        row = row + self.rawnum[left : right]
        matrix.append(row)
      # 上三角补全到完整矩阵
      m = np.array(matrix)
      matrix = (np.triu(m, k=1).T + np.triu(m, k=0)).tolist()
    
    # 下三角，不包含对角全0
    elif self.EDGE_WEIGHT_FORMAT == "LOWER_ROW":
      # 数据长度应该是：d + d-1 + d-2 +...+ 1 = (1+d)*d/2
      d = self.DIMENSION
      self.rawnum = self.rawnum.reverse()
      if not len(self.rawnum) == int((1+d)*d/2-d):
        raise Exception("获取的raw num数据量不对")
      for i in range(d):
        # 由于自己有0，第一行填1个0，第二行补2个，第n行补n个
        row = [0 for j in range(i+1)]
        # left = sum 0 d-1 d-2 
        if i == 0:
          left = 0
        else:
          left = int( d*(i-1) -(i-1)*i/2 )
        # right = sum d-1 d-2 d-3 ... = int(d*i -(1+i)i/2)
        right = int( d*i -(1+i)*i/2 )
        row = row + self.rawnum[left : right]
        matrix.append(row)
      # 下三角补全到完整矩阵
      m = np.array(matrix)
      matrix = (np.tril(m, k=1).T + np.tril(m, k=0)).tolist()

    elif self.EDGE_WEIGHT_FORMAT == "FULL_MATRIX":
      # 数据长度应该是：d**2
      d = self.DIMENSION
      if not len(self.rawnum) == int(d**2):
        raise Exception("获取的raw num数据量不对")
      for i in range(d):
        row = self.rawnum[i:i+d]
        matrix.append(row)

    elif self.EDGE_WEIGHT_FORMAT == "UNDIFINED":
      d = self.DIMENSION
      # 进行辨识
      #  "FULL_MATRIX"
      if len(self.rawnum) == int(d**2):
        for i in range(d):
          row = self.rawnum[i:i+d]
          matrix.append(row)
      # 下三角，不包含对角全0
      elif len(self.rawnum) == int((1+d)*d/2-d):
        for i in range(d):
          # 由于自己有0，第一行填1个0，第二行补2个，第n行补n个
          row = [0 for j in range(i+1)]
          # left = sum 0 d-1 d-2 
          if i == 0:
            left = 0
          else:
            left = int( d*(i-1) -(i-1)*i/2 )
          # right = sum d-1 d-2 d-3 ... = int(d*i -(1+i)i/2)
          right = int( d*i -(1+i)*i/2 )
          row = row + self.rawnum[left : right]
          matrix.append(row)
        # 上三角补全到完整矩阵
        m = np.array(matrix)
        matrix = (np.triu(m, k=1).T + np.triu(m, k=0)).tolist()
      # 上下三角，不包含对角全0
      elif len(self.rawnum) == int((1+d)*d/2-d):
        if self.rawnum[2] == 0:
          # 下三角
          for i in range(d):
            # 由于自己有0，第一行填1个0，第二行补2个，第n行补n个
            row = [0 for j in range(i+1)]
            # left = sum 0 d-1 d-2 
            if i == 0:
              left = 0
            else:
              left = int( d*(i-1) -(i-1)*i/2 )
            # right = sum d-1 d-2 d-3 ... = int(d*i -(1+i)i/2)
            right = int( d*i -(1+i)*i/2 )
            row = row + self.rawnum[left : right]
            matrix.append(row)
          # 上三角补全到完整矩阵
          m = np.array(matrix)
          matrix = (np.tril(m, k=1).T + np.tril(m, k=0)).tolist()
        else:
          for i in range(d):
            # 由于自己有0，第一行不填0，第二行补一个，第n行补n-1个
            row = [0 for j in range(i)]
            # left = sum 0 d d-1 \
            left = int( i*d-(0+i-1)*i/2 )
            right = int( (i+1)*d-(0+i)*(i+1)/2 )
            # right = sum d d-1 d-2 ... = i*d-(0+i-1)*i/2
            row = row + self.rawnum[left : right]
            matrix.append(row)
          # 上三角补全到完整矩阵
          m = np.array(matrix)
          matrix = (np.triu(m, k=1).T + np.triu(m, k=0)).tolist()
      else:
        raise Exception("储存矩阵形式为定义，且未辨识成功，长度不符合已有类型")

    return matrix
  
  # 坐标表转换邻接表
  # 根据数据类型，返回数据的邻接表，有的算法需要这个
  def coordinate_2_table(self, optimize=True):
    """
    当数据为坐标地图：
      坐标表方式储存，每个x->y都需要计算。
      规定城市编号从一开始
    进一步：
      #todo
      优化计算，只用算一半
    retrun:
      字典好查询
      或者是表
    optimize:
      是否使用优化计算方法获取矩阵
    """
    whole_table = {}
    # ATSP 问题邻接矩阵不对称
    if optimize and self.TYPE != 'ATSP':
      for i in range(1,1+self.DIMENSION):
        for j in range(1,1+self.DIMENSION):
          if j >= i :
            whole_table[(i,j)] = self.cal_a_distance_by_coordinate(i,j)
      # 减小计算量（#todo能不能用矩阵对称算法？矩阵转置，然后相加）
      for i in range(1,1+self.DIMENSION):
        for j in range(1,1+self.DIMENSION):
          if j < i :
            whole_table[(i,j)] = whole_table[(j,i)]
    else:
      for i in range(1,1+self.DIMENSION):
        for j in range(1,1+self.DIMENSION):
          whole_table[(i,j)] = self.cal_a_distance_by_coordinate(i,j)

    return whole_table

  def coordinate_2_matrix(self, optimize=True):
    """
    当数据为坐标地图：
      坐标表方式储存，每个x->y都需要计算。
      规定城市编号从一开始
      第一行意为：从城市1到。。。
      注意索引是0开始
    进一步：
      #todo
      优化计算，只用算一半
      使用numpy，对角矩阵获取，转置，相加，即可
    """
    whole_matrix = []
    if optimize and self.TYPE != 'ATSP':
      for i in range(1,1+self.DIMENSION):
        thisRow = []
        for j in range(1,1+self.DIMENSION):
          if i<j: #上三角
            thisRow.appned(self.cal_a_distance_by_coordinate(i,j))
          else:
            thisRow.appned(0)
        whole_matrix.append(thisRow)
      # 上三角补全到完整矩阵
      m = np.array(whole_matrix)
      whole_matrix = (np.triu(m, k=1).T + np.triu(m, k=0)).tolist()
    else:
      for i in range(1,1+self.DIMENSION):
        thisRow = []
        for j in range(1,1+self.DIMENSION):
          thisRow.appned(self.cal_a_distance_by_coordinate(i,j))
        whole_matrix.append(thisRow)

    return whole_matrix

  # 坐标表转换到矩阵
  def table_2_matrix(self,table):
    """
    table:
      字典类型，x-》y索引距离
    """
    whole_matrix = []
    for i in range(1,1+self.DIMENSION):
      thisRow = []
      for j in range(1,1+self.DIMENSION):
        thisRow.appned(table[(i,j)])
      whole_matrix.append(thisRow)

    return whole_matrix

  # 矩阵转邻接表
  def matex_2_table(self,matrix):
    """   
      矩阵储存， 需要提取表
      区分情况，是否对称等
    """
    whole_table = {}
    for i in range(1,1+self.DIMENSION):
      for j in range(1,1+self.DIMENSION):
        whole_table[(i,j)] = matrix[i-1][j-1]

    return whole_table
    
